sudo: required

# Ugh, `services:` must be in the matrix, or we get `docker: command not found`
#   https://github.com/travis-ci/travis-ci/issues/5142
matrix:
  include:
    - env: ['from_image=ubuntu:14.04', gcc_version=4.9]
      services: [docker]
    # Unlike 14.04, this Debian Stable has 4.9 as the system compiler, so
    # there is no risk of 4.8/4.9 ABI incompatibilities.
    - env: ['from_image=debian:8.6', gcc_version=4.9]
      services: [docker]
    - env: ['from_image=ubuntu:16.04', gcc_version=5]
      services: [docker]

script:
  # Travis seems to get confused when `matrix:` is used with `language:`
  - sudo apt-get install python2.7
  # We don't want to write this script inline because of Travis kludginess --
  # it looks like it escapes " and \ in scripts when using `matrix:`.
  - ./travis-emit-dockerfile.sh
  - docker build .
